# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 80
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: 49.235.109.153
    # 端口，默认为6379
    port: 1000
    # 数据库索引
    database: 0
    # 密码
    password: zlgg@965
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
# elasticsearch 配置
  elasticsearch:
    rest:
      username: elastic
      password: zlgg@965
      uris:
        - http://localhost:9200
#FTP配置
ftp:
  hostname: 49.235.109.153
  port: 21
  username: ftp
  password: zlgg@965
  save-path: /pub

#slf4g
logging:
  config: classpath:logback-spring.xml



